version: '2'

# Named volumes
volumes:
    # MySQL Data
    ambientum-mysql-data:
        driver: local

services:
    # MySQL (5.7)
    db:
        image: mysql:5.7
        container_name: ambientum-mysql
        volumes:
            - ambientum-mysql-data:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    # PHP (with Nginx)
    # you can change from nginx to apache, just change session 'image'
    app:
        image: ambientum/php:7.2-nginx
        container_name: ambientum-app
        volumes:
            - ${APP_PATH}:/var/www/app
        ports:
            - "80:8080"
        links:
            - db:mysql